backend:
  name: github
  repo: sebhal92/gabinet-beata-test
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "cennik"
    label: "Cennik usług"
    folder: "_data"
    create: false
    extension: "yml"
    format: "yaml"
    identifier_field: "kategorie"
    fields:
      - label: "Zawartość YAML cennika"
        name: "kategorie"
        type: "text"
        widget: "text"
