backend:
  name: github
  repo: sebhal92/gabinet-beata-test
  branch: main
  auth_type: implicit

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "cennik"
    label: "Cennik usług"
    files:
      - file: "_data/cennik.yml"
        label: "Edycja Cennika"
        name: "cennik_uslug"
        fields:
          - label: "Kategorie i zabiegi"
            name: "kategorie"
            type: "list"
            fields:
              - label: "Nazwa kategorii"
                name: "nazwa"
                type: "string"
                required: false
              - label: "Pozycje (Zabiegi)"
                name: "pozycje"
                type: "list"
                required: false
                fields:
                  - label: "Nazwa zabiegu"
                    name: "zabieg"
                    type: "string"
                  - label: "Czas trwania"
                    name: "czas"
                    type: "string"
                  - label: "Cena (np. 150 zł lub zostaw puste, by był przycisk Zapytaj)"
                    name: "cena"
                    type: "string"
                    required: false
