backend:
  name: github
  repo: sebhal92/gabinet-beata-test
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "cennik"
    label: "Cennik usług"
    folder: "_data"
    create: false
    delete: false
    extension: "yml"
    format: "yaml"
    fields:
      - label: "Kategorie"
        name: "kategorie"
        widget: "list"
        fields:
          - label: "Nazwa kategorii"
            name: "nazwa"
            widget: "string"
          - label: "Pozycje"
            name: "pozycje"
            widget: "list"
            fields:
              - label: "Zabieg"
                name: "zabieg"
                widget: "string"
              - label: "Czas"
                name: "czas"
                widget: "string"
              - label: "Cena"
                name: "cena"
                widget: "string"
